[package]
name = "bm_client"
version = "0.1.0"
authors = ["Chris Greenaway <cjgreenaway@gmail.com>"]

[dependencies]
byteorder = "0.3.10"
encoding = "0.2"
rand = "0.3"
sodiumoxide = "0.0.5"
time = "0.1.26"

