[package]
name = "rubbem"
version = "0.1.0"
authors = ["Chris Greenaway"]

[dependencies.bm_client]
path = "../bm_client"

[dependencies]
gtk = "0.0.7"
#git = "https://github.com/gtk-rs/gtk"
#features = ["gtk_3_6"]
